### ISSUE TITLE
Build error for flexbe-mirror

### ISSUE THREAD

**Issue by bchoineubility** [bmwcarit/meta-ros#1077]
Hi

I am trying to build flexbe-mirror for yocto kirkstone and got build error as following:

```
ERROR: flexbe-mirror-2.3.3-1-r0 do_install: ExecutionError('/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/temp/run.do_install.1242157', 1, None, None)
ERROR: Logfile of failure stored in: /home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/temp/log.do_install.1242157
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/bchoi/work/official_ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/flexbe-behavior-engine/flexbe-core_2.3.3-1.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/flexbe-behavior-engine/flexbe-msgs_2.3.3-1.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/rclpy/rclpy_3.3.10-1.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-core/glibc/glibc_2.35.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/gcc/gcc-cross_11.4.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/gcc/gcc-runtime_11.4.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/python/python3_3.10.13.bb:do_populate_sysroot', '/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/python/python3-installer_0.5.1.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/python/python3-setuptools_59.5.0.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/python/python3-wheel_0.37.1.bb:do_populate_sysroot', 'virtual:native:/home/bchoi/work/official_ros_humble_build/sources/poky/meta/recipes-devtools/python/python3_3.10.13.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['flexbe-core', 'flexbe-msgs', 'rclpy', 'glibc', 'gcc-cross-aarch64', 'gcc-runtime', 'python3', 'quilt-native', 'patch-native', 'pseudo-native', 'python3-installer-native', 'python3-setuptools-native', 'python3-wheel-native', 'python3-native', 'python3-flit-core-native', 'unzip-native', 'rcl', 'rmw-implementation', 'rcl-logging-interface', 'rmw-implementation-cmake', 'rcutils', 'rcl-yaml-param-parser', 'rosidl-runtime-c', 'rcpputils', 'rcl-action', 'unique-identifier-msgs', 'rcl-lifecycle', 'pybind11-vendor', 'rmw', 'std-msgs', 'tf2-ros-py', 'std-srvs', 'libtool-native', 'attr-native', 'binutils-cross-aarch64', 'texinfo-dummy-native', 'gnu-config-native', 'flex-native', 'gmp-native', 'zstd-native', 'zlib-native', 'libmpc-native', 'linux-libc-headers', 'xz-native', 'mpfr-native', 'sqlite3-native', 'libtirpc-native', 'openssl-native', 'util-linux-libuuid-native', 'libffi-native', 'ncurses-native', 'readline-native', 'bzip2-native', 'libnsl2-native', 'gdbm-native', 'readline', 'zlib', 'libnsl2', 'libxcrypt', 'libffi', 'ncurses', 'gdbm', 'opkg-utils', 'xz', 'sqlite3', 'openssl', 'util-linux-libuuid', 'bzip2', 'libtirpc', 'libgcc', 'rosidl-default-generators', 'builtin-interfaces', 'action-msgs', 'rosidl-default-runtime', 'tracetools', 'rcl-interfaces', 'rcl-logging-spdlog', 'rmw-fastrtps-dynamic-cpp', 'ament-index-cpp', 'rmw-cyclonedds-cpp', 'rmw-fastrtps-cpp', 'libyaml-vendor', 'libyaml', 'rosidl-typesupport-interface', 'lifecycle-msgs', 'python3-pybind11', 'rosidl-typesupport-cpp', 'rosidl-typesupport-c', 'gettext-minimal-native', 'm4-native', 'perl-native', 'rosidl-generator-cpp', 'rosidl-runtime-cpp', 'fastcdr', 'rosidl-typesupport-fastrtps-c', 'fastrtps-cmake-module', 'python-cmake-module', 'rosidl-typesupport-fastrtps-cpp', 'rosidl-generator-py', 'rosidl-typesupport-introspection-cpp', 'rosidl-typesupport-introspection-c', 'rmw-fastrtps-shared-cpp', 'spdlog', 'spdlog-vendor', 'fastrtps', 'rmw-dds-common', 'iceoryx-binding-c', 'cyclonedds', 'boost', 'rosidl-cmake', 'make-native', 'rosidl-generator-c', 'ament-index-python', 'rosidl-cli', 'python3-numpy', 'fmt', 'foonathan-memory-vendor', 'asio', 'libtinyxml2', 'iceoryx-posh', 'iceoryx-hoofs', 'icu', 'foonathan-memory', 'acl', 'autoconf-archive', 'attr']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| Traceback (most recent call last):
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
|     return _run_code(code, main_globals, None,
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/runpy.py", line 86, in _run_code
|     exec(code, run_globals)
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/__main__.py", line 92, in <module>
|     _main(sys.argv[1:], "python -m installer")
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/__main__.py", line 88, in _main
|     installer.install(source, destination, {})
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/_core.py", line 86, in install
|     for name, module, attr, section in parse_entrypoints(entrypoints_text):
|   File "/home/bchoi/work/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-mirror/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/utils.py", line 221, in parse_entrypoints
|     assert match
| AssertionError
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/bchoi/work/official_ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/flexbe-behavior-engine/flexbe-mirror_2.3.3-1.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2483 tasks of which 2474 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/bchoi/work/official_ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/flexbe-behavior-engine/flexbe-mirror_2.3.3-1.bb:do_install
Summary: There was 1 WARNING message.
Summary: There was 1 ERROR message, returning a non-zero exit code.
```

BR,
Mark

**Comment by robwoolley** [comment]
Thanks for submitting the issue.  This is 1 of about 100 failures that I'm seeing right now with ros-image-world.

I took a quick look, it appears that flexbe_mirror is triggering some sort of assertion inside of the Python installer module.   I'm not sure exactly what the problem is.  I'll need to do some more research.

**Comment by codewithpassion** [comment]
Hey Mark, Rob

I've come across this before when trying to get some Iron recipes built. 
The problem is that `flexbe-mirror` s `setup.py`  has two lines:
https://github.com/FlexBE/flexbe_behavior_engine/blob/humble/flexbe_mirror/setup.py#L25-L26

Those lines do not have a `:main` nominator. I'm not familiar with the python installer and I'm not sure why this happens during the yocto install. Potentially it's a version mismatch. 
But I went ahead and manged to get `flexbe-mirror` installed adding a `bbappend` file with this:

`flexbe-mirror_%.bbappend` 
```
RDEPENDS:${PN} += "bash"

do_configure:prepend() {
    # Fix for error: python3.10/site-packages/installer/utils.py", line 222, in parse_entrypoints
    # assert match
    # This is caused by an invalid entry in the setup.py file
    sed -i "/'mirror_state = flexbe_mirror.mirror_state',/d" setup.py
    sed -i "/'flexbe_mirror = flexbe_mirror.flexbe_mirror',/d" setup.py
}
```
Now, writing this, maybe a solution would be to add `:main` to those lines rather than delete them. 
@bchoineubility, maybe you could adjust the `bbappend` file above to add that and see how you go.

If you could report back to how things work for you, that would be great!

Regards,
Dom

**Comment by bchoineubility** [comment]
Hi @codewithpassion,

Many thanks for reply. I have also doubt it and looking into how regular expression filter it. but, I had no idea how to fix it correctly.

Thanks for your reply again I will adopt and test it in advance.

BR, 
Mark

**Comment by bchoineubility** [comment]
Hi @codewithpassion,

Many thanks. it work for me as well.

Hi @robwoolley,
May I close this issue or remain for more investigation to clarify?

BR,
Mark

**Comment by robwoolley** [comment]
Thanks for tracking this down.  I think deleting the lines is the correct approach.   I filed an issue upstream to get feedback from the maintainer of the flexbe behaviour engine: https://github.com/FlexBE/flexbe_behavior_engine/issues/15

**Comment by dcconner** [comment]
Noted.  I'll try to have an Iron update pushed out later this week.

**Comment by robwoolley** [comment]
The fix was merged upstream.
